@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImZpcnN0bmFtZSI6ImFkbWluIiwibGFzdG5hbWUiOiJ1c2VyIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpZCI6IjEwYzFjMjk5LTEyY2QtNDliOC04OTZjLTU4ODZhZWNkYmI5NyIsInVzZXJyb2xlIjoiR0xPQkFMX2FETUlOIiwidXNlcnNjb3BlcyI6WyJvcmcxL2V1cm9wZS9nZXJtYW55L2Jlcmxpbi9hZG1pbi8iLCJvcmcxL2V1cm9wZS9nZXJtYW55L211bmljaC9hZG1pbi8iLCJvcmcxL2V1cm9wZS9nZXJtYW55L2ZyYW5rZnVydC9kZXZlbG9wZXIvIl0sInBhc3N3b3JkIjoiJDJhJDEwJGUzSFE5Q1lZWFpycnlnWWkzcE51ei5UMDdNSUdZNHZBeUdBdHE4M2xKR2ZJMnZZd3NFMDRlIiwiY3JlYXRlZF9hdCI6IjIwMjQtMDUtMjUgMTM6NTg6MDUuMTU0NzEyNCArMDIwMCBNUyJ9LCJhdWQiOiJnaXRodWIuY29tL0Jhc2lsbGljYS9nb2xhbmctZ3VpZGUiLCJleHAiOjE3MTY3MjQ3MDMsImlhdCI6MTcxNjYzODMwMywiaXNzIjoiZ2l0aHViLmNvbS9CYXNpbGxpY2EvZ29sYW5nLWd1aWRlIn0.dHYyRybp5RbMiugwv3PCFlGEVf30NMb_ZDO_FAlHZy4

### LOGIN
POST http://localhost:8080/v1/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin@gmail.com",
    "password": "password"
}

###
DELETE http://localhost:8080/v2/user/delete HTTP/1.1

### create user
POST http://localhost:8080/v1/user/create HTTP/1.1
Content-Type: application/json

{
    "firstname": "regular",
    "lastname": "user",
    "email": "regularuser@gmail.com",
    "password": "password",
    "userrole": "REGULAR_USER",
    "userscopes": [
        "org1/europe/germany/berlin/admin/",
        "org1/europe/germany/munich/admin/",
        "org1/europe/germany/frankfurt/developer/"
    ]
}

### get users
GET http://localhost:8080/v1/user/get HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### get user
GET http://localhost:8080/v1/user/get/b13ac0ce-6902-404c-94ab-dcdf0c9ac41b HTTP/1.1
Content-Type: application/json

### delete user
DELETE http://localhost:8080/v1/user/delete/b13ac0ce-6902-404c-94ab-dcdf0c9ac41b HTTP/1.1
Content-Type: application/json


### form submission
POST http://localhost:8080/v1/misc/form  HTTP/1.1
Content-Type: application/x-www-form-urlencoded

name=tonie
&email=email@example.com
&message=some boring message